-- Jejak simplified geographic catalog and prepared static data.
--
-- Static facts are loaded by scheduled ETL. User requests never invoke an LLM
-- for these rows.

begin;

set local search_path = public, extensions, pg_catalog;

select pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('jejak:schema-migrations', 0)
);

create table if not exists public.regions (
    id                  integer generated by default as identity primary key,
    parent_id           integer references public.regions(id) on delete restrict,
    code                varchar(64) not null unique,
    name                varchar(160) not null,
    region_type         varchar(30) not null,
    geometry            extensions.geometry(MultiPolygon, 4326),
    source              varchar(80),
    source_updated_at   timestamptz,
    is_supported        boolean not null default false,
    created_at          timestamptz not null default pg_catalog.now(),
    updated_at          timestamptz not null default pg_catalog.now(),
    constraint regions_code_ck
        check (
            code = pg_catalog.lower(code)
            and code ~ '^[a-z0-9][a-z0-9_-]{0,63}$'
        ),
    constraint regions_type_ck
        check (region_type in (
            'country', 'province', 'regency', 'city', 'district',
            'neighborhood', 'grid', 'metro'
        ))
);

create table if not exists public.institutions (
    id                  integer generated by default as identity primary key,
    code                varchar(80) not null unique,
    name                varchar(240) not null,
    institution_type    varchar(30) not null,
    website             text,
    source              varchar(100),
    source_url          text,
    is_active            boolean not null default true,
    created_at          timestamptz not null default pg_catalog.now(),
    updated_at          timestamptz not null default pg_catalog.now(),
    constraint institutions_code_ck
        check (
            code = pg_catalog.lower(code)
            and code ~ '^[a-z0-9][a-z0-9_-]{0,79}$'
        ),
    constraint institutions_type_ck
        check (institution_type in (
            'university', 'polytechnic', 'school', 'training_provider', 'other'
        )),
    constraint institutions_website_ck
        check (website is null or website ~ '^https://'),
    constraint institutions_source_url_ck
        check (source_url is null or source_url ~ '^https://')
);

create table if not exists public.places (
    id                  bigint generated always as identity (maxvalue 9007199254740991) primary key,
    region_id           integer not null references public.regions(id) on delete restrict,
    institution_id      integer references public.institutions(id) on delete restrict,
    osm_type            varchar(10),
    osm_id              bigint,
    name                text not null,
    category            varchar(30) not null,
    latitude            double precision not null,
    longitude           double precision not null,
    address             text,
    website             text,
    phone               varchar(40),
    operator            text,
    osm_tags            jsonb not null default '{}'::jsonb,
    source              varchar(50) not null,
    source_url          text,
    observed_at         timestamptz,
    is_active            boolean not null default true,
    created_at          timestamptz not null default pg_catalog.now(),
    updated_at          timestamptz not null default pg_catalog.now(),
    constraint places_osm_type_ck
        check (osm_type is null or osm_type in ('node', 'way', 'relation')),
    constraint places_osm_identity_ck
        check ((osm_type is null and osm_id is null)
            or (osm_type is not null and osm_id is not null and osm_id > 0)),
    constraint places_category_ck
        check (category in (
            'campus', 'transit_stop', 'station', 'hospital',
            'public_facility', 'other'
        )),
    constraint places_latitude_ck
        check (latitude between -90 and 90),
    constraint places_longitude_ck
        check (longitude between -180 and 180),
    constraint places_osm_tags_object_ck
        check (pg_catalog.jsonb_typeof(osm_tags) = 'object'),
    constraint places_source_url_ck
        check (source_url is null or source_url ~ '^https://')
);

create unique index if not exists places_osm_identity_uq
    on public.places (osm_type, osm_id)
    where osm_type is not null and osm_id is not null;

create table if not exists public.region_data (
    id                  bigint generated always as identity (maxvalue 9007199254740991) primary key,
    region_id           integer not null references public.regions(id) on delete restrict,
    metric              varchar(80) not null,
    numeric_value       numeric,
    text_value          text,
    json_value          jsonb,
    unit                varchar(30),
    evidence_type       varchar(20) not null,
    period_start        date,
    period_end          date,
    source              varchar(100) not null,
    source_url          text,
    published_at        timestamptz,
    retrieved_at        timestamptz,
    sample_size         integer,
    confidence          numeric(5,4),
    limitations         text,
    is_sample            boolean not null default false,
    created_at          timestamptz not null default pg_catalog.now(),
    updated_at          timestamptz not null default pg_catalog.now(),
    constraint region_data_evidence_ck
        check (evidence_type in ('observed', 'estimated', 'derived', 'unavailable')),
    constraint region_data_period_ck
        check (period_end is null or period_start is null or period_end >= period_start),
    constraint region_data_sample_size_ck
        check (sample_size is null or sample_size >= 0),
    constraint region_data_confidence_ck
        check (confidence is null or confidence between 0 and 1),
    constraint region_data_value_shape_ck
        check (
            (evidence_type = 'unavailable'
                and (case when numeric_value is not null then 1 else 0 end
                    + case when text_value is not null then 1 else 0 end
                    + case when json_value is not null then 1 else 0 end) = 0)
            or
            (evidence_type <> 'unavailable'
                and (case when numeric_value is not null then 1 else 0 end
                    + case when text_value is not null then 1 else 0 end
                    + case when json_value is not null then 1 else 0 end) = 1)
        ),
    constraint region_data_source_url_ck
        check (source_url is null or source_url ~ '^https://')
);

create table if not exists public.institution_data (
    id                  bigint generated always as identity (maxvalue 9007199254740991) primary key,
    institution_id      integer not null references public.institutions(id) on delete restrict,
    campus_place_id     bigint,
    metric              varchar(80) not null,
    numeric_value       numeric,
    text_value          text,
    json_value          jsonb,
    unit                varchar(30),
    data_scope          varchar(20) not null,
    academic_year       varchar(20),
    period_start        date,
    period_end          date,
    source              varchar(100) not null,
    source_url          text,
    published_at        timestamptz,
    retrieved_at        timestamptz not null default pg_catalog.now(),
    evidence_type       varchar(20) not null,
    confidence          numeric(5,4),
    limitations         text,
    is_sample            boolean not null default false,
    created_at          timestamptz not null default pg_catalog.now(),
    constraint institution_data_scope_ck
        check (data_scope in ('institution', 'campus', 'program', 'unknown')
            and (data_scope <> 'campus' or campus_place_id is not null)
            and (data_scope not in ('institution', 'unknown') or campus_place_id is null)),
    constraint institution_data_evidence_ck
        check (evidence_type in ('observed', 'estimated', 'derived', 'unavailable')),
    constraint institution_data_period_ck
        check (period_end is null or period_start is null or period_end >= period_start),
    constraint institution_data_confidence_ck
        check (confidence is null or confidence between 0 and 1),
    constraint institution_data_value_shape_ck
        check (
            (evidence_type = 'unavailable'
                and (case when numeric_value is not null then 1 else 0 end
                    + case when text_value is not null then 1 else 0 end
                    + case when json_value is not null then 1 else 0 end) = 0)
            or
            (evidence_type <> 'unavailable'
                and (case when numeric_value is not null then 1 else 0 end
                    + case when text_value is not null then 1 else 0 end
                    + case when json_value is not null then 1 else 0 end) = 1)
        ),
    constraint institution_data_source_url_ck
        check (source_url is null or source_url ~ '^https://')
);

create index if not exists regions_parent_type_idx
    on public.regions (parent_id, region_type);
create index if not exists regions_geometry_gist
    on public.regions using gist (geometry);
create index if not exists institutions_name_idx
    on public.institutions (name);
create index if not exists places_region_category_idx
    on public.places (region_id, category, is_active);
create index if not exists places_institution_idx
    on public.places (institution_id, category);
create index if not exists region_data_lookup_idx
    on public.region_data (region_id, metric, period_end desc);
create index if not exists region_data_metric_idx
    on public.region_data (metric, evidence_type);
create index if not exists institution_data_lookup_idx
    on public.institution_data (institution_id, metric, academic_year);
create index if not exists institution_data_campus_idx
    on public.institution_data (campus_place_id, metric, period_end desc);

create trigger regions_updated_at_trg
before update on public.regions
for each row execute function private.touch_updated_at();

create trigger institutions_updated_at_trg
before update on public.institutions
for each row execute function private.touch_updated_at();

create trigger places_updated_at_trg
before update on public.places
for each row execute function private.touch_updated_at();

create trigger region_data_updated_at_trg
before update on public.region_data
for each row execute function private.touch_updated_at();

-- A composite FK keeps campus facts attached to their actual institution.
alter table public.places
    add constraint places_id_institution_uq unique (id, institution_id),
    add constraint places_institution_category_ck
        check (institution_id is null or category = 'campus');
alter table public.institution_data
    add constraint institution_data_campus_institution_fk
        foreign key (campus_place_id, institution_id)
        references public.places (id, institution_id) on delete restrict;

commit;
